version: '3.3'
services:

  selenium-hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - GRID_MAX_SESSION=10  

  chrome:
    image: selenium/node-chrome-debug:3.14
    # enable this for debugging through vnc viewer
    # ports:
    #   - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - DEBUG=1
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
  firefox:
    image: selenium/node-firefox-debug:3.14
    # enable this for debugging through vnc viewer
    # ports:
    #   - "5901:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - DEBUG=1
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10

  test:
    build: .
    environment:
      - VISUAL_DROID_PASSWORD
      - URL_VISUAL_DROID
      - BUILDKITE
      - BUILDKITE_BRANCH              
      - BUILDKITE_BUILD_ID    
      - BROWSER
      - BRANCH_SHA
      - COMPARE_SHA
      - PROJECT_NAME
      - BROWSERSTACK_USERNAME
      - BROWSERSTACK_ACCESS_KEY
      - TEST_TYPE
    depends_on:
      - selenium-hub
      - chrome
      - firefox